### ISSUE TITLE
微博超话签到和原神兑换码报错

### ISSUE THREAD

**Issue by Womsxd** [y1ndan/genshinhelper#10]
超话报错：
`2021-05-23 09:43:42 INFO You have 1 「微博超话签到」 account configured.
2021-05-23 09:43:42 INFO Preparing to perform tasks for account 1...
C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py:842: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((
2021-05-23 09:43:42 ERROR 👻 No.1:
    Empty follow data
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\genshinhelper\__init__.py", line 34, in __run_sign
    result = func(cookie).run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\genshinhelper\weibo.py", line 77, in run
    raise Exception('Empty follow data')
Exception: Empty follow data`
兑换码报错
`2021-05-23 09:43:43 ERROR 👻 No.1:
    😳 27970: 5月18日后连续签到1天以上才能领取礼包，快去签到吧！
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\genshinhelper\__init__.py", line 34, in __run_sign
    result = func(cookie).run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\genshinhelper\weibo.py", line 236, in run
    code = self.get_code(id)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\genshinhelper\weibo.py", line 219, in get_code
    raise Exception(f'😳 {id}: {response["msg"]}')
Exception: 😳 27970: 5月18日后连续签到1天以上才能领取礼包，快去签到吧！`
微博超话看其他issues的Android环境抓包出来的数据和软件不兼容导致的，然后兑换码这个正常吗？

**Comment by y1ndan** [comment]
登录ka.sina.com.cn看看有没有领成功，领码提示这里有bug

**Comment by Womsxd** [comment]
> ka.sina.com.cn

无，卡箱是空

**Comment by y1ndan** [comment]
> 无，卡箱是空

那就是没签到成功。安卓抓包暂时没有研究出来

**Comment by 49470488** [comment]
> > 无，卡箱是空
> 
> 那就是没签到成功，要签到一定天数才能领。安卓抓包暂时没有研究出来

大佬，我微博超话签到也是报这个错误，iphone抓的包，求助
![QQ截图20210523180608](https://user-images.githubusercontent.com/71637330/119256119-a2eebf00-bbf1-11eb-895f-1c306bcbda15.jpg)

**Comment by 49470488** [comment]
谢谢，原项目我已经可以签到了😉

y1ndan ***@***.***> 於 2021年6月2日週三 下午11:49寫道：

**Comment by y1ndan** [comment]
ok
