### ISSUE TITLE
更新了python-pip后装不上了

### ISSUE THREAD

**Issue by onlymash** [y1ndan/genshinhelper#24]
```
$ pip --version
pip 20.3.2 from /usr/lib/python3.9/site-packages/pip (python 3.9)
```
```
$ pip install --upgrade genshinhelper
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: genshinhelper in ./.local/lib/python3.9/site-packages (1.4.0)
Collecting genshinhelper
  Downloading genshinhelper-1.4.0-py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 400 kB/s
  Downloading genshinhelper-1.4.0.tar.gz (43 kB)
     |████████████████████████████████| 43 kB 912 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y5b9nf4p/genshinhelper_765afccdf38147b6a9f73ddebd8321b7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y5b9nf4p/genshinhelper_765afccdf38147b6a9f73ddebd8321b7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5ybwlmuo
         cwd: /tmp/pip-install-y5b9nf4p/genshinhelper_765afccdf38147b6a9f73ddebd8321b7/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y5b9nf4p/genshinhelper_765afccdf38147b6a9f73ddebd8321b7/setup.py", line 53, in <module>
        install_requires=load_requirements('requirements.txt'),
      File "/tmp/pip-install-y5b9nf4p/genshinhelper_765afccdf38147b6a9f73ddebd8321b7/setup.py", line 10, in load_requirements
        with Path(filename).open() as f:
      File "/usr/lib/python3.9/pathlib.py", line 1242, in open
        return io.open(self, mode, buffering, encoding, errors, newline,
      File "/usr/lib/python3.9/pathlib.py", line 1110, in _opener
        return self._accessor.open(self, flags, mode)
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/38/95/dca66037aa75e74c5dd8b5ea8fe0768c661e21ed0f40811140051863571d/genshinhelper-1.4.0.tar.gz#sha256=34eb30d2a62c6bd0047efcd8913e25640b5c5680fe4b05aa7ba5b55160ba08f2 (from https://pypi.org/simple/genshinhelper/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by y1ndan** [comment]
卸载重装

**Comment by y1ndan** [comment]
Closing due to inactivity.
