### ISSUE TITLE
配置文件不支持CRON_SIGNIN 这个参数吗？

### ISSUE THREAD

**Issue by xy9860** [y1ndan/genshinhelper#25]
我设置了以后还是默认的运行时间，这儿还有一个警告和一个异常，是不影响运行的吧
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:842: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((
2021-06-22 17:28:03 ERROR Unknown check-in status
2021-06-22 17:28:03 ERROR TRACEBACK
Traceback (most recent call last):
  File "/app/genshinhelper/__init__.py", line 61, in __run_sign
    result = func(cookie).run()
  File "/app/genshinhelper/weibo.py", line 97, in run
    raise GenshinHelperException('Unknown check-in status')

**Comment by y1ndan** [comment]
`CRON_SIGNIN `是docker独有的，不支持配置文件方式使用。

报错影响运行，请检查cookie和相关配置。

**Comment by xy9860** [comment]
破案了Unknown check-in status是因为我没有关注原神超话
