### ISSUE TITLE
pushplus推送异常

### ISSUE THREAD

**Issue by zhilincom** [y1ndan/genshinhelper#42]
<html>
<body>

用户token自测是有效的，但是总是推送失败，异常信息如下：

```
2021-08-22 08:56:58 ERROR pushplus 😳
{'code': 999, 'msg': '无效的用户token', 'data': None}
2021-08-22 08:56:58 ERROR TRACEBACK
Traceback (most recent call last):
File "/app/genshinhelper/__init__.py", line 116, in main
notifiers.send2all(
File "/app/genshinhelper/notifiers/__init__.py", line 49, in send2all
get_notifier(notifier).send(text, status, desp)
File "/app/genshinhelper/notifiers/pushplus.py", line 21, in send
return self.push('post', url, data=data)
File "/app/genshinhelper/notifiers/basenotifier.py", line 54, in push
raise NotificationError(f'{self.name} 😳\n{response}')
genshinhelper.exceptions.NotificationError: pushplus 😳
{'code': 999, 'msg': '无效的用户token', 'data': None}
```

</body>
</html>

**Comment by Yaklo** [comment]
因为换pushplus换域名了，还有就是现在不支持markdown语法信息看着都是挤在一起的
你修改一下下面的内容就可以正常推送了，推送格式等开发者修吧
src\genshinhelprt\notifiers\pushplus.py
第13行 url内容修改为http://pushplus.hxtrip.com/send

**Comment by AXdouB** [comment]
我临时改了一下 已经开PR了 不妨先试着按照这个修改
我测试过已经可以使用了 格式做到换行正常
https://github.com/y1ndan/genshinhelper/pull/44/files

**Comment by Yaklo** [comment]
找到问题了
你应该用的是旧网站，百度直接搜就是旧的，建议换成新的
http://www.pushplus.plus/
