### ISSUE TITLE
运行报错了，是我的cookies没有设置正确吗

### ISSUE THREAD

**Issue by xy9860** [y1ndan/genshinhelper#8]
2021-05-21 19:17:38 INFO Running genshinhelper with docker
2021-05-21 19:17:38 INFO Starting signing
2021-05-21 19:17:38 INFO 🌀 genshinhelper v1.1.1
2021-05-21 19:17:38 INFO Running process...
2021-05-21 19:17:38 INFO You have 1 「米游社原神签到」 account configured.
2021-05-21 19:17:38 INFO Preparing to perform tasks for account 1...
2021-05-21 19:17:39 INFO 当前账号绑定了 1 个角色
2021-05-21 19:17:39 ERROR 👻 No.1:
    'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/genshinhelper/__init__.py", line 34, in __run_sign
    result = func(cookie).run()
  File "/app/genshinhelper/genshin.py", line 48, in wrapper
    result_list.append(func(self, *args, **kwargs))
  File "/app/genshinhelper/genshin.py", line 106, in run
    today = sign_info.get('data', {}).get('today', '1970-01-01')
AttributeError: 'NoneType' object has no attribute 'get'
2021-05-21 19:17:39 INFO RESULT:
〓米游社原神签到〓
🔰 ✔ 0 · ✖ 1
👻 No.1:
    'NoneType' object has no attribute 'get'

2021-05-21 19:17:39 ERROR Process finished with exit code -1

**Comment by drrrMikado** [comment]
在论坛退出账号，重新登陆下。我之前也是这个问题，通过重登解决了。
